### ISSUE TITLE
opencv3.3 is listed as a dependency but the install dependencies script makes no effort to install them

### ISSUE THREAD

**Issue by saket424** [intel-iot-devkit/smart-video-workshop#5]

**Comment by saket424** [comment]
I followed the steps outlined in https://www.pyimagesearch.com/2018/05/28/ubuntu-18-04-how-to-install-opencv/ to install opencv3.4.1 and then I was able to make progress and get all the workshop tutorials working on an UP2+MovidiusNCS

**Comment by saket424** [comment]
@priyanka-bagade 
Thanks for the workshop yesterday and the cool demo. It took some work to set up the various install scripts but now I am a happy camper

source ~/cv3/bin/activate
export SV=/opt/intel/workshop/smart-video-workshop/
source /opt/intel/computer_vision_sdk/bin/setupvars.sh
export models=/opt/intel/computer_vision_sdk/deployment_tools/intel_models/

cd /opt/intel/computer_vision_sdk/deployment_tools/inference_engine/samples/build/intel64/Release 

./interactive_face_detection_sample -i /dev/video0 -m $models/face-detection-retail-0004/FP16/face-detection-retail-0004.xml -d MYRIAD -m_ag $models/age-gender-recognition-retail-0013/FP32/age-gender-recognition-retail-0013.xml -d_ag CPU -m_hp $models/head-pose-estimation-adas-0001/FP16/head-pose-estimation-adas-0001.xml -d_hp GPU -m_em $models/emotions-recognition-retail-0003/FP16/emotions-recognition-retail-0003.xml -d_em GPU

**Comment by priyanka-bagade** [comment]
Glad to know that your system is fully setup and ready to build new exciting applications. 
The OpenVINO toolkit package comes with OpenCV. You should not need to install it separately.
Were you facing any issue with OpenCV after installing OpenVINO?

**Comment by PoonamZ** [comment]
@priyanka-bagade I am able to successfully run the security_barrier_camera_demo. But at the time of interactive_face_detection_demo I am getting the error message like 

[ ERROR ] Cannot make shared blob! The blob type cannot be used to store objects of current precision
 
Can you please help me to solve the problem.
